# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/berlna/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),berlna)

$(call add-radio-file-sha1-checked,radio/bluetooth.img,f03693c9c493e89587f564a22d374ca8caf20559)
$(call add-radio-file-sha1-checked,radio/dsp.img,72c78cc1886db44fdb7893f8734a002552151a50)

endif
